import { NextResponse } from 'next/server';
import { initAdmin } from '@/lib/firebase-admin';

export async function GET() {
    try {
        const adminApp = await initAdmin();
        if (!adminApp) {
            return NextResponse.json({ error: 'Failed to initialize admin' }, { status: 500 });
        }

        const db = adminApp.firestore();

        // Fetch 10 most recent users, contracts, and payments
        const [usersSnap, contractsSnap, paymentsSnap] = await Promise.all([
            db.collection('users').orderBy('createdAt', 'desc').limit(10).get(),
            db.collection('contracts').orderBy('createdAt', 'desc').limit(10).get(),
            db.collection('payments').where('status', '==', 'succeeded').orderBy('createdAt', 'desc').limit(10).get()
        ]);

        const activities: any[] = [];

        usersSnap.forEach(doc => {
            const data = doc.data();
            activities.push({
                id: doc.id,
                type: 'user_signup',
                title: `New user joined: ${data.name || 'Anonymous'}`,
                description: `User with email ${data.email || 'N/A'} registered.`,
                timestamp: data.createdAt?.toDate?.()?.toISOString() || new Date().toISOString(),
                category: 'Users'
            });
        });

        contractsSnap.forEach(doc => {
            const data = doc.data();
            activities.push({
                id: doc.id,
                type: 'contract_created',
                title: `New contract created: ${data.title || 'Untitled'}`,
                description: `Contract generated by owner ${data.ownerId.substring(0, 8)}...`,
                timestamp: data.createdAt?.toDate?.()?.toISOString() || new Date().toISOString(),
                category: 'Contracts'
            });
        });

        paymentsSnap.forEach(doc => {
            const data = doc.data();
            activities.push({
                id: doc.id,
                type: 'payment_received',
                title: `Payment received: ฿${(data.amount / 100).toLocaleString()}`,
                description: `Successful payment for user ${data.userId.substring(0, 8)}...`,
                timestamp: data.createdAt?.toDate?.()?.toISOString() || new Date().toISOString(),
                category: 'Finance'
            });
        });

        // Sort all activities by timestamp descending
        activities.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

        return NextResponse.json({ activities: activities.slice(0, 10) });
    } catch (error: any) {
        console.error('ADMIN_ACTIVITY_ERROR', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
